---
- name: ping server
  ping:

- name: update apt cache
  apt:
    update_cache: yes

- name: install gnupg, apt-transport-https
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: present

- name: Get kibana.7.17.14
  ansible.builtin.get_url:  
    url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.17.14-amd64.deb 
    dest: /home/artvoadm2/

- name: Install kibana
  apt:
    deb: /home/artvoadm2/kibana-7.17.14-amd64.deb

- name: Copy config file for kibana
  copy:
    src: /home/ubuntu/infra/ansible/roles/kibana/files/kibana.yml
    dest: /etc/kibana
    mode: 0644
    owner: artvoadm2
    group: root

- name: restarted kibana
  service:
    name: kibana
    state: restarted   

- name: systemctl enable kibana
  ansible.builtin.service:
    name: kibana
    enabled: yes
